DROP DATABASE IF EXISTS company_NEW;
CREATE DATABASE Company_NEW;

USE Company_NEW;

CREATE TABLE Employees(
	emp_id INT AUTO_INCREMENT PRIMARY KEY,
    emp_name VARCHAR(50),
    salary INT,
    dept_id INT
);

CREATE TABLE Logtable(
	log_id INT AUTO_INCREMENT PRIMARY KEY,
    action_type VARCHAR(50),
    description TEXT,
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Deletelog(
	log_id INT AUTO_INCREMENT PRIMARY KEY,
    emp_name VARCHAR(50),
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

